---

# These tasks installs mysql and starts the mysql service if it's not active


- name: Install Mysql
  apt:
    name:
      - mysql-server
      - python3-mysqldb
    state: present
  tags: mysql

- name: Ensure the mysql service is started
  service:
    name: mysql
    state: started
  tags: mysql
