---

# These tasks add the php repo, installs php8.1 and other php8.1 extensions

- name: Add ondrej php repository
  apt_repository:
    repo: '{{ php_repo }}'
    update_cache: yes
  tags: php

- name: Install PHP and other dependencies
  apt:
    name:
      - php8.1
      - libapache2-mod-php8.1
      - php8.1-mysql
      - php8.1-common
      - php8.1-xml
      - php8.1-xmlrpc
      - php8.1-curl
      - php8.1-gd
      - php8.1-imagick
      - php8.1-cli
      - php8.1-dev
      - php8.1-imap
      - php8.1-mbstring
      - php8.1-opcache
      - php8.1-soap
      - php8.1-zip
      - php8.1-intl
    state: present
  tags: php

